# Generated by hand for TeaWither A09 (no local Django runtime)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gardens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeafProvenance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("villageGroup", models.CharField(max_length=120, verbose_name="鲜叶村组")),
                ("pickingDate", models.DateField(verbose_name="采摘日")),
                ("registrar", models.CharField(max_length=80, verbose_name="登记人")),
                ("batch", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="strip", to="gardens.witherbatch", verbose_name="关联批次")),
                ("garden", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="strips", to="gardens.garden", verbose_name="所属茶园")),
            ],
            options={
                "verbose_name": "茶青溯源条",
                "verbose_name_plural": "茶青溯源条",
                "ordering": ["-pickingDate", "-id"],
            },
        ),
    ]
